<!-- div id="music163player" -->
    <!-- iframe frameborder="no" border="0" marginwidth="0" marginheight="0" width=330 height=86 src="//music.163.com/outchain/player?type=2&id=521784134&auto=1&height=66" --><!-- /iframe -->
<!-- /div -->

<embed src="http://www.xiami.com/widget/51707075_274326798_235_346_FF8719_494949_0/collectPlayer.swf" type="application/x-shockwave-flash" width="235" height="346" wmode="opaque"></embed>
